/**
 * Aliases de sistema → nome original na TACO (ADR-024). Os termos são normalizados
 * (sem acento, minúsculos) no seed. Cobre os padrões de estado de P6.2: grãos, carnes e
 * leguminosas cozidos; "frango" = peito grelhado; ovo sem preparo = cozido.
 */
export const ALIASES: readonly (readonly [alias: string, tacoName: string])[] = [
  // Cereais e massas
  ['arroz', 'Arroz, tipo 1, cozido'],
  ['arroz branco', 'Arroz, tipo 1, cozido'],
  ['arroz cozido', 'Arroz, tipo 1, cozido'],
  ['arroz branco cozido', 'Arroz, tipo 1, cozido'],
  ['arroz integral', 'Arroz, integral, cozido'],
  ['arroz integral cozido', 'Arroz, integral, cozido'],
  ['arroz cru', 'Arroz, tipo 1, cru'],
  ['macarrao', 'Macarrão, trigo, cru'],
  ['macarrao instantaneo', 'Macarrão, instantâneo'],
  ['miojo', 'Macarrão, instantâneo'],
  ['macarrao a bolonhesa', 'Macarrão, molho bolognesa'],
  ['aveia', 'Aveia, flocos, crua'],
  ['aveia em flocos', 'Aveia, flocos, crua'],
  ['granola', 'Aveia, flocos, crua'],
  ['cuscuz', 'Cuscuz, de milho, cozido com sal'],
  ['cuscuz nordestino', 'Cuscuz, de milho, cozido com sal'],
  ['cuscuz paulista', 'Cuscuz, paulista'],
  ['tapioca', 'Tapioca, com manteiga'],
  ['farofa', 'Mandioca, farofa, temperada'],
  ['farinha de mandioca', 'Farinha, de mandioca, torrada'],
  ['farinha de trigo', 'Farinha, de trigo'],
  ['fuba', 'Milho, fubá, cru'],
  ['polenta', 'Polenta, pré-cozida'],
  ['milho', 'Milho, verde, enlatado, drenado'],
  ['milho verde', 'Milho, verde, enlatado, drenado'],
  ['pipoca', 'Pipoca, com óleo de soja, sem sal'],
  // Pães e biscoitos
  ['pao', 'Pão, trigo, francês'],
  ['pao frances', 'Pão, trigo, francês'],
  ['paes franceses', 'Pão, trigo, francês'],
  ['pao de sal', 'Pão, trigo, francês'],
  ['pao careca', 'Pão, trigo, francês'],
  ['pao de forma', 'Pão, trigo, forma, integral'],
  ['pao de forma integral', 'Pão, trigo, forma, integral'],
  ['pao integral', 'Pão, trigo, forma, integral'],
  ['pao de queijo', 'Pão, de queijo, assado'],
  ['pao doce', 'Pão, trigo, sovado'],
  ['torrada', 'Biscoito, salgado, cream cracker'],
  ['torradas', 'Biscoito, salgado, cream cracker'],
  ['bolacha', 'Biscoito, salgado, cream cracker'],
  ['cream cracker', 'Biscoito, salgado, cream cracker'],
  ['biscoito de agua e sal', 'Biscoito, salgado, cream cracker'],
  ['biscoito maisena', 'Biscoito, doce, maisena'],
  ['biscoito recheado', 'Biscoito, doce, recheado com chocolate'],
  ['biscoito de polvilho', 'Biscoito, polvilho doce'],
  ['bolo', 'Bolo, pronto, chocolate'],
  ['bolo de chocolate', 'Bolo, pronto, chocolate'],
  ['bolo de milho', 'Bolo, pronto, milho'],
  // Leguminosas
  ['feijao', 'Feijão, carioca, cozido'],
  ['feijao carioca', 'Feijão, carioca, cozido'],
  ['feijao cozido', 'Feijão, carioca, cozido'],
  ['feijao preto', 'Feijão, preto, cozido'],
  ['feijao fradinho', 'Feijão, fradinho, cozido'],
  ['feijao tropeiro', 'Feijão tropeiro mineiro'],
  ['lentilha', 'Lentilha, cozida'],
  ['grao de bico', 'Grão-de-bico, cru'],
  ['ervilha', 'Ervilha, enlatada, drenada'],
  ['tofu', 'Soja, queijo (tofu)'],
  ['leite de soja', 'Soja, extrato solúvel, natural, fluido'],
  // Aves
  ['frango', 'Frango, peito, sem pele, grelhado'],
  ['frango grelhado', 'Frango, peito, sem pele, grelhado'],
  ['peito de frango', 'Frango, peito, sem pele, grelhado'],
  ['peito de frango grelhado', 'Frango, peito, sem pele, grelhado'],
  ['file de frango', 'Frango, peito, sem pele, grelhado'],
  ['file de frango grelhado', 'Frango, peito, sem pele, grelhado'],
  ['frango cozido', 'Frango, peito, sem pele, cozido'],
  ['frango desfiado', 'Frango, peito, sem pele, cozido'],
  ['frango cru', 'Frango, peito, sem pele, cru'],
  ['coxa de frango', 'Frango, coxa, sem pele, cozida'],
  ['sobrecoxa', 'Frango, sobrecoxa, sem pele, assada'],
  ['frango a milanesa', 'Frango, filé, à milanesa'],
  ['peru', 'Peru, congelado, assado'],
  // Carnes
  ['carne', 'Carne, bovina, patinho, sem gordura, grelhado'],
  ['bife', 'Carne, bovina, patinho, sem gordura, grelhado'],
  ['patinho', 'Carne, bovina, patinho, sem gordura, grelhado'],
  ['carne grelhada', 'Carne, bovina, patinho, sem gordura, grelhado'],
  ['carne moida', 'Carne, bovina, acém, moído, cozido'],
  ['carne moida cozida', 'Carne, bovina, acém, moído, cozido'],
  ['acem', 'Carne, bovina, acém, sem gordura, cozido'],
  ['contra file', 'Carne, bovina, contra-filé, sem gordura, grelhado'],
  ['contrafile', 'Carne, bovina, contra-filé, sem gordura, grelhado'],
  ['hamburguer', 'Hambúrguer, bovino, grelhado'],
  ['carne de porco', 'Porco, lombo, assado'],
  ['lombo', 'Porco, lombo, assado'],
  ['lombo de porco', 'Porco, lombo, assado'],
  ['bisteca', 'Porco, bisteca, grelhada'],
  ['pernil', 'Porco, pernil, assado'],
  ['presunto', 'Presunto, sem capa de gordura'],
  ['mortadela', 'Mortadela'],
  ['salame', 'Salame'],
  // Peixes
  ['peixe', 'Merluza, filé, assado'],
  ['merluza', 'Merluza, filé, assado'],
  ['salmao', 'Salmão, sem pele, fresco, grelhado'],
  ['salmao grelhado', 'Salmão, sem pele, fresco, grelhado'],
  ['atum', 'Atum, conserva em óleo'],
  ['atum em lata', 'Atum, conserva em óleo'],
  ['sardinha', 'Sardinha, conserva em óleo'],
  ['sardinha em lata', 'Sardinha, conserva em óleo'],
  ['camarao', 'Camarão, Rio Grande, grande, cozido'],
  ['pescada', 'Pescada, filé, frito'],
  // Ovos
  ['ovo', 'Ovo, de galinha, inteiro, cozido/10minutos'],
  ['ovos', 'Ovo, de galinha, inteiro, cozido/10minutos'],
  ['ovo cozido', 'Ovo, de galinha, inteiro, cozido/10minutos'],
  ['ovos cozidos', 'Ovo, de galinha, inteiro, cozido/10minutos'],
  ['ovo frito', 'Ovo, de galinha, inteiro, frito'],
  ['ovos fritos', 'Ovo, de galinha, inteiro, frito'],
  ['clara', 'Ovo, de galinha, clara, cozida/10minutos'],
  ['claras', 'Ovo, de galinha, clara, cozida/10minutos'],
  ['clara de ovo', 'Ovo, de galinha, clara, cozida/10minutos'],
  ['ovo de codorna', 'Ovo, de codorna, inteiro, cru'],
  // Laticínios
  ['iogurte', 'Iogurte, natural'],
  ['iogurte natural', 'Iogurte, natural'],
  ['iogurte desnatado', 'Iogurte, natural, desnatado'],
  ['queijo', 'Queijo, minas, frescal'],
  ['queijo minas', 'Queijo, minas, frescal'],
  ['queijo branco', 'Queijo, minas, frescal'],
  ['queijo mussarela', 'Queijo, mozarela'],
  ['mussarela', 'Queijo, mozarela'],
  ['muçarela', 'Queijo, mozarela'],
  ['queijo prato', 'Queijo, prato'],
  ['parmesao', 'Queijo, parmesão'],
  ['ricota', 'Queijo, ricota'],
  ['leite em po', 'Leite, de vaca, integral, pó'],
  ['leite condensado', 'Leite, condensado'],
  ['creme de leite', 'Creme de Leite'],
  ['manteiga', 'Manteiga, com sal'],
  ['margarina', 'Margarina, com óleo interesterificado, com sal (65%de lipídeos)'],
  // Tubérculos
  ['batata', 'Batata, inglesa, cozida'],
  ['batata cozida', 'Batata, inglesa, cozida'],
  ['batata inglesa', 'Batata, inglesa, cozida'],
  ['batata doce', 'Batata, doce, cozida'],
  ['batata doce cozida', 'Batata, doce, cozida'],
  ['batata frita', 'Batata, inglesa, frita'],
  ['mandioca', 'Mandioca, cozida'],
  ['aipim', 'Mandioca, cozida'],
  ['macaxeira', 'Mandioca, cozida'],
  ['mandioca frita', 'Mandioca, frita'],
  ['mandioquinha', 'Batata, baroa, cozida'],
  ['batata baroa', 'Batata, baroa, cozida'],
  ['inhame', 'Inhame, cru'],
  ['cara', 'Cará, cozido'],
  // Frutas
  ['banana', 'Banana, prata, crua'],
  ['bananas', 'Banana, prata, crua'],
  ['banana prata', 'Banana, prata, crua'],
  ['banana nanica', 'Banana, nanica, crua'],
  ['maca', 'Maçã, Fuji, com casca, crua'],
  ['laranja', 'Laranja, pêra, crua'],
  ['suco de laranja', 'Laranja, pêra, suco'],
  ['mamao', 'Mamão, Papaia, cru'],
  ['mamao papaia', 'Mamão, Papaia, cru'],
  ['mamao formosa', 'Mamão, Formosa, cru'],
  ['melancia', 'Melancia, crua'],
  ['melao', 'Melão, cru'],
  ['uva', 'Uva, Itália, crua'],
  ['morango', 'Morango, cru'],
  ['morangos', 'Morango, cru'],
  ['abacaxi', 'Abacaxi, cru'],
  ['manga', 'Manga, Tommy Atkins, crua'],
  ['abacate', 'Abacate, cru'],
  ['kiwi', 'Kiwi, cru'],
  ['goiaba', 'Goiaba, vermelha, com casca, crua'],
  ['tangerina', 'Tangerina, Poncã, crua'],
  ['mexerica', 'Tangerina, Poncã, crua'],
  ['ameixa', 'Ameixa, crua'],
  ['maracuja', 'Maracujá, cru'],
  ['limao', 'Limão, tahiti, cru'],
  ['agua de coco', 'Coco, água de'],
  // Verduras e legumes
  ['alface', 'Alface, crespa, crua'],
  ['salada de alface', 'Alface, crespa, crua'],
  ['tomate', 'Tomate, com semente, cru'],
  ['cenoura', 'Cenoura, crua'],
  ['cenoura cozida', 'Cenoura, cozida'],
  ['brocolis', 'Brócolis, cozido'],
  ['couve', 'Couve, manteiga, refogada'],
  ['couve flor', 'Couve-flor, cozida'],
  ['espinafre', 'Espinafre, Nova Zelândia, refogado'],
  ['abobrinha', 'Abobrinha, italiana, refogada'],
  ['abobora', 'Abóbora, cabotian, cozida'],
  ['beterraba', 'Beterraba, cozida'],
  ['chuchu', 'Chuchu, cozido'],
  ['pepino', 'Pepino, cru'],
  ['cebola', 'Cebola, crua'],
  ['repolho', 'Repolho, branco, cru'],
  ['salada de legumes', 'Salada, de legumes, cozida no vapor'],
  // Gorduras, doces e outros
  ['azeite', 'Azeite, de oliva, extra virgem'],
  ['azeite de oliva', 'Azeite, de oliva, extra virgem'],
  ['oleo', 'Óleo, de soja'],
  ['oleo de soja', 'Óleo, de soja'],
  ['maionese', 'Maionese, tradicional com ovos'],
  ['acucar', 'Açúcar, refinado'],
  ['acucar mascavo', 'Açúcar, mascavo'],
  ['mel', 'Mel, de abelha'],
  ['chocolate', 'Chocolate, ao leite'],
  ['chocolate amargo', 'Chocolate, meio amargo'],
  ['doce de goiaba', 'Goiaba, doce em pasta'],
  ['goiabada', 'Goiaba, doce em pasta'],
  ['amendoim', 'Amendoim, torrado, salgado'],
  ['castanha de caju', 'Castanha-de-caju, torrada, salgada'],
  ['castanha do para', 'Castanha-do-Brasil, crua'],
  ['castanhas', 'Castanha-do-Brasil, crua'],
  ['cafe', 'Café, infusão 10%'],
  ['cafe preto', 'Café, infusão 10%'],
  ['refrigerante', 'Refrigerante, tipo cola'],
  ['coca cola', 'Refrigerante, tipo cola'],
  ['guarana', 'Refrigerante, tipo guaraná'],
  ['cerveja', 'Cerveja, pilsen 2'],
  ['coxinha', 'Coxinha de frango, frita'],
  ['pastel', 'Pastel, de carne, frito'],
  ['pastel de queijo', 'Pastel, de queijo, frito'],
];
